/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bfc3cf85-4a21-4ca4-8bbf-ca67a27fc7e1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_kGX0dNuXc",
    "aws_user_pools_web_client_id": "3itvchkumom9govkrrqh8ll658",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fzqt7duo6vcidjfjazrc6doobi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wyxjpwuw7reapjnvrz2q5u5ylq",
    "aws_user_files_s3_bucket": "timely-tweet-media-store184035-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
